<div class="content" id="aboutContent">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <p class="lead"> London Squash and Fitness Club Privacy Policy</p>
                <p>This Privacy Policy describes the commitment to privacy of the London Squash and Fitness Club (the Club) and explains the principles that guide us in protecting the privacy and confidentiality of personal information.</p>
                <p>Personal information is information about an identifiable individual. It includes, but is not limited to, health and financial information. This Privacy Policy applies to the Club’s Board of Directors, members, participants and employees and other persons and organizations who act for, or on behalf of, the Club.</p>
                <p>Access to personal information is restricted to directors, officers, employees, licensed representatives, and other persons or organizations acting for, or on behalf of, the Club, who need the information in order to provide services to the member or the Club.</p>
                <p>ACCOUNTABILITY The Club is responsible for personal information in its control, including information that may be transferred to a service provider performing services for, or on behalf of, the Club. The Club has established this Privacy Policy, and procedures and practices, to safeguard such personal information.</p>
                <p>PURPOSES The Club identifies the purposes for which it collects personal information either before or at the time of collection.</p>
                <p>CONSENT The Club collects, uses and discloses personal information only with the consent of the individual, or as otherwise allowed by law. Consent to the collection, use, or disclosure of personal information may be express or implied, as appropriate. Individuals may withdraw their consent at any time, subject to legal or contractual restrictions and considerations.</p>
                <p>COLLECTION The Club only collects personal information that is necessary for the purposes identified. Personal information is collected d directly from the individual, and may, with consent or as otherwise allowed by law, be collected from other sources.</p>
                <p>ACCURACY The Club uses reasonable efforts to ensure that personal information is accurate and complete for the purposes for which it is to be used. Page 1 of 2 USE,</p>
                <p>DISCLOSURE & RETENTION Personal information is not, without consent, used or disclosed to a third party for any purpose other than that for which it was collected, unless such use or disclosure is required or allowed by law. The Club retains personal information only as long as necessary to fulfill the identified purpose or as otherwise required or allowed by law.</p>
                <p>SAFEGUARDS The Club protects the security and confidentiality of personal information with safeguards appropriate to the sensitivity of the information.</p>
                <p>INDIVIDUAL ACCESS An individual may request to be informed of the existence, use and disclosure of personal information pertaining to him or her. The Club will provide appropriate access to such information that it holds. If the Club determines not to provide access to personal information, we will provide an explanation. Individuals may request the correction of personal information the Club holds about them, and if we find that what we have is incorrect, we will correct it.</p>
                <p>USING OUR WEB SITE You can access our website home page and browse our site without disclosing your personal data.</p>
                <p>USE OF COOKIES A cookie is a small text file containing a unique identification number that is transferred from a website to the hard drive of your computer so that the website may identify separate visitors to the site and track users’ activities on the website. A cookie will not let a website know any personally identifiable information about you, such as your real name and address. The Club uses cookies only to keep track of how many people visit the Club’s website and how frequently each page is visited. Each individual movement of any user cannot be tracked while on the site. Cookies are only used to track page popularity for statistical purposes and to improve the quality of the site. (For more information on cookies, please check your browser’s settings.)</p>
                <p>LINKS ON OUR WEBSITE Because the Club wants your website experience to be informational and resourceful, our Website provides a number of links to third party sites. The Club assumes no responsibility for the information practices of sites you are able to access through our site. We encourage you to review each site's privacy policy before disclosing any personally identifiable information.</p>
                <p>CONCERNS, ENQUIRIES or REQUESTS Any concern, inquiry or request related to privacy should be made in writing.</p>
                <p><a href="contact.html">Contact the club via our online form here.</a></p>
                <p>The Directors – 2018/19 </p>
            </div>
        </div>
    </div>
</div>
